/**
 * 热门滑雪场初始数据
 *
 * 使用方法：
 * 1. 在微信开发者工具中，打开"云开发 → 数据库"
 * 2. 创建集合 "resorts"
 * 3. 点击集合名称，选择"导入"
 * 4. 选择本文件，导入类型选择 "JSON"
 */

module.exports = [
  {
    name: '万龙滑雪场',
    type: 'outdoor',
    province: '河北省',
    city: '张家口市',
    address: '崇礼区红花梁',
    latitude: 40.973,
    longitude: 115.499,
    facilities: {
      hasRental: true,
      hasParking: true,
      hasRestaurant: true,
      hasHotel: true,
      hasNightSkiing: true,
    },
    openHour: 8,
    closeHour: 17,
    tickets: [
      { type: '成人全天票', price: 580 },
      { type: '成人半天票', price: 400 },
      { type: '儿童全天票', price: 320 },
    ],
    trails: {
      totalCount: 32,
      beginner: 6,
      intermediate: 16,
      advanced: 8,
      expert: 2,
    },
    popularity: 95,
    rating: 4.5,
  },
  {
    name: '将军山滑雪场',
    type: 'outdoor',
    province: '新疆维吾尔自治区',
    city: '阿勒泰地区',
    address: '阿勒泰市将军山',
    latitude: 47.844,
    longitude: 88.139,
    facilities: {
      hasRental: true,
      hasParking: true,
      hasRestaurant: true,
      hasHotel: true,
      hasNightSkiing: true,
    },
    openHour: 10,
    closeHour: 18,
    tickets: [
      { type: '成人全天票', price: 268 },
      { type: '成人半天票', price: 198 },
    ],
    trails: {
      totalCount: 40,
      beginner: 12,
      intermediate: 18,
      advanced: 8,
      expert: 2,
    },
    popularity: 98,
    rating: 4.8,
  },
  {
    name: '太舞滑雪场',
    type: 'outdoor',
    province: '河北省',
    city: '张家口市',
    address: '崇礼区营岔村',
    latitude: 40.962,
    longitude: 115.467,
    facilities: {
      hasRental: true,
      hasParking: true,
      hasRestaurant: true,
      hasHotel: true,
      hasNightSkiing: true,
    },
    openHour: 9,
    closeHour: 16,
    tickets: [
      { type: '成人全天票', price: 520 },
      { type: '儿童全天票', price: 280 },
    ],
    trails: {
      totalCount: 28,
      beginner: 8,
      intermediate: 12,
      advanced: 6,
      expert: 2,
    },
    popularity: 92,
    rating: 4.6,
  },
  {
    name: '成都融创雪世界',
    type: 'indoor',
    province: '四川省',
    city: '成都市',
    address: '都江堰市至臻路',
    latitude: 30.987,
    longitude: 103.648,
    facilities: {
      hasRental: true,
      hasParking: true,
      hasRestaurant: true,
      hasHotel: true,
      hasNightSkiing: false,
    },
    openHour: 10,
    closeHour: 22,
    tickets: [
      { type: '4小时平日票', price: 388 },
      { type: '4小时周末票', price: 488 },
      { type: '全天票', price: 688 },
    ],
    trails: {
      totalCount: 7,
      beginner: 3,
      intermediate: 3,
      advanced: 1,
      expert: 0,
    },
    popularity: 88,
    rating: 4.3,
  },
  {
    name: '广州融创雪世界',
    type: 'indoor',
    province: '广东省',
    city: '广州市',
    address: '花都区凤凰北路',
    latitude: 23.404,
    longitude: 113.224,
    facilities: {
      hasRental: true,
      hasParking: true,
      hasRestaurant: true,
      hasHotel: true,
      hasNightSkiing: false,
    },
    openHour: 11,
    closeHour: 21,
    tickets: [
      { type: '4小时平日票', price: 388 },
      { type: '全天票', price: 658 },
    ],
    trails: {
      totalCount: 5,
      beginner: 2,
      intermediate: 2,
      advanced: 1,
      expert: 0,
    },
    popularity: 85,
    rating: 4.2,
  },
  {
    name: '云顶滑雪公园',
    type: 'outdoor',
    province: '河北省',
    city: '张家口市',
    address: '崇礼区太子城',
    latitude: 40.954,
    longitude: 115.496,
    facilities: {
      hasRental: true,
      hasParking: true,
      hasRestaurant: true,
      hasHotel: true,
      hasNightSkiing: true,
    },
    openHour: 9,
    closeHour: 16,
    tickets: [
      { type: '成人全天票', price: 490 },
      { type: '成人半天票', price: 360 },
    ],
    trails: {
      totalCount: 41,
      beginner: 10,
      intermediate: 19,
      advanced: 10,
      expert: 2,
    },
    popularity: 90,
    rating: 4.4,
  },
  {
    name: '密苑云顶乐园',
    type: 'outdoor',
    province: '河北省',
    city: '张家口市',
    address: '崇礼区四台嘴乡',
    latitude: 40.948,
    longitude: 115.506,
    facilities: {
      hasRental: true,
      hasParking: true,
      hasRestaurant: true,
      hasHotel: true,
      hasNightSkiing: true,
    },
    openHour: 8,
    closeHour: 17,
    tickets: [
      { type: '成人全天票', price: 680 },
      { type: '儿童全天票', price: 360 },
    ],
    trails: {
      totalCount: 35,
      beginner: 8,
      intermediate: 17,
      advanced: 8,
      expert: 2,
    },
    popularity: 87,
    rating: 4.5,
  },
];
